#!/usr/bin/env python3
"""Write Prometheus file_sd target files from the inventory (ADR 0008).

Reads one JSON object on stdin, {job: [target groups]}, generated by
OpenTofu from inventory/lab.yaml (terraform_data.monitoring_targets in
proxmox/opentofu/monitoring.tf), and writes /etc/prometheus/targets/<job>.json.

Each file is replaced atomically, so Prometheus (which watches the directory)
never reads a half-written file. Job files no longer in the input are removed.
"""
import json
import os
import sys
import tempfile

DIR = "/etc/prometheus/targets"

jobs = json.load(sys.stdin)
os.makedirs(DIR, mode=0o755, exist_ok=True)

for job, groups in jobs.items():
    fd, tmp = tempfile.mkstemp(dir=DIR, prefix=f".{job}.")
    with os.fdopen(fd, "w") as f:
        json.dump(groups, f, indent=2, sort_keys=True)
        f.write("\n")
    os.chmod(tmp, 0o644)
    os.replace(tmp, os.path.join(DIR, f"{job}.json"))

for name in os.listdir(DIR):
    if name.endswith(".json") and name[: -len(".json")] not in jobs:
        os.remove(os.path.join(DIR, name))

total = sum(len(t["targets"]) for groups in jobs.values() for t in groups)
print(f"targets: {len(jobs)} jobs, {total} targets written to {DIR}")
